language: node_js
node_js:
  - "12"
  - "10"

env:
  - GRAPHQL_VERSION='0.13'
  - GRAPHQL_VERSION='latest'
  - GRAPHQL_VERSION='rc'

install:
  - npm config set spin=false
  - npm install

script:
  - if [[ $GRAPHQL_VERSION == "latest" ]]; then
      npm run lint;
    fi
  - if [[ $GRAPHQL_VERSION == "latest" ]]; then
      npm run format:check;
    fi
  - npm run compile
  - npm install graphql@$GRAPHQL_VERSION
  - npm run test

# Allow Travis tests to run in containers.
sudo: false
