name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-16-16-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-16-16-yarn
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Lint
        run: yarn lint
  build:
    name: Type Check on GraphQL v${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graphql_version: [14, 15]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-16-${{matrix.graphql_version}}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-16-${{matrix.graphql_version}}-yarn
      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Build
        run: yarn ts:check
  test:
    name: Unit Test on Node ${{matrix.node_version}} and GraphQL v${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12, 16]
        graphql_version: [14, 15]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{matrix.node_version}}-${{matrix.graphql_version}}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.node_version}}-${{matrix.graphql_version}}-yarn
      - name: Use GraphQL v${{matrix.graphql_version}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Cache Jest
        uses: actions/cache@v2
        with:
          path: .cache/jest
          key: ${{ runner.os }}-${{matrix.node_version}}-${{matrix.graphql_version}}-jest-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.node_version}}-${{matrix.graphql_version}}-jest-
      - name: Test
        run: yarn test --ci
        env:
          CI: true
  federation-benchmark:
    name: Federation Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-16-16-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-16-16-yarn
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Build
        run: yarn build
      - name: Setup K6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6
      - name: GraphQL API
        working-directory: ./benchmark/federation
        run: |
          yarn start &
          yarn wait-on tcp:3000
      - name: Federation
        run: k6 -e ENDPOINT=federation run benchmark/federation/test.js
      - name: Stitching
        run: k6 -e ENDPOINT=stitching run benchmark/federation/test.js
