name: Website Deployment
on:
  push:
    branches:
      - master

jobs:
  deploy-website:
    name: Deploy Website
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1
      - name: Configure Git Credientials
        run: |
          git config --global user.email "ardatan@users.noreply.github.com"
          git config --global user.name "ardatan"
          echo "machine github.com login ardatan password ${{secrets.GH_API_TOKEN}}" > ~/.netrc
      - name: Add origin remote and refetch master
        run: |
          git remote rm origin
          git remote add origin "https://github.com/${{github.repository}}"
          git fetch
          git checkout master
          git reset --hard
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-14-15-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-14-15-yarn-
      - name: Install Dependencies using Yarn
        run: yarn install && git checkout yarn.lock
      - name: Deploy 🚀
        run: yarn deploy:website
        env:
          GIT_USER: ardatan
